%
%function [Xl,Xr,ITD]=itdamprofilenoisegen(f1,f2,ITD,Fs,seed)
%
%       FILE NAME       : ITD AM PROFILE NOISE GEN
%       DESCRIPTION     : Generates a a binaural noise signal with a 
%                         desired ITD Profile. This is done time warping 
%                         the time axis of the signal by the desired ITD 
%                         profile and interpolating at the original samples 
%                         times.
%
%       f1              : Lower noise cutoff frequency (Hz)
%       f2              : Upper noise cutoff frequency (Hz)
%       ITD             : Desired ITD profile (sampled at Fs)
%       Fs              : Sampling Frequency
%       seed            : Seed for random number generator
%                         (Default = no seed)
%
% (C) Monty A. Escabi, Jan 2009
%
function [Xl,Xr,ITD]=itdamprofilenoisegen(f1,f2,ITD,Fs,seed)

%Input Arguments
if nargin<5
    seed=sum(100*clock);
end

%Time Axis and warped time axis. ITDs are generated by time warping the 
%signal for the left and right audio channels
M=length(ITD);
t=(1:M)/Fs;
tpl=t+ITD/2;
tpr=t-ITD/2;

plot(tpl-tpr)


%Gaussian Bandlimited Noise
%X=noiseblfft(f1,f2,Fs,M);
X=noiseblh(f1,f2,Fs,M,seed,'y');

%Time Warping the left and right sounds
Xl=interp1(tpl,X,t,'cubic');
Xr=interp1(tpr,X,t,'cubic');

%BandPass Filtering to remove spectral splatter due to time warping and
%interpolation artifact (i.e., crappy interpolator)
ATT=60;
H=bandpass(f1,f2,.1*(f2-f1)/2,Fs,ATT,'n');
N=(length(H)-1)/2;
NFFT=2^nextpow2(N+M);
Xl=convfft(Xl,H,N,NFFT);
Xr=convfft(Xr,H,N,NFFT);
Xl=Xl(1:M);
Xr=Xr(1:M);