%
%function [Xl,Xr,ITD]=itdrandamnoisegen(f1,f2,ITDMax,Fmb,Fs,M,seed,seed2)
%
%       FILE NAME       : ITD RAND AM NOISE GEN
%       DESCRIPTION     : Generates a random noise "binaural beat". This is
%                         done time warping the time axis of the signal by 
%                         a random ITD profile and interpolating at the 
%                         original samples times. The random ITD profile is
%                         uniformly distributed with a maximum ITD
%                         excursion of ITDMax. The maximum rate of change
%                         of the ITD profile is given by Fmb.
%
%       f1              : Lower noise cutoff frequency (Hz)
%       f2              : Upper noise cutoff frequency (Hz)
%       ITDMax          : Maximum ITD (micro sec)
%       Fmb             : ITD Upper Beat Frequency (Hz)
%       Fs              : Sampling Frequency
%       M               : Number of Samples
%       seed            : Seed for random number generator
%                         (Default = no seed)
%       seed2           : Seed for random ITD profile (Default = no seed)
%
% (C) Monty A. Escabi, Jan 2009
%
function [Xl,Xr,ITD]=itdrandamnoisegen(f1,f2,ITDMax,Fmb,Fs,M,seed,seed2)

%Input Arguments
if nargin<7
    seed=sum(100*clock);
end
pause(.5)
if nargin<8
    seed2=sum(1000*clock);
end

%Time Axis and warped time axis. ITDs are generated by time warping the 
%signal for the left and right audio channels
t=(1:M)/Fs;
[ITD]=ITDMax/1E6*(noiseunif(Fmb,Fs,M,seed2)-.5)*2;
tpl=t+ITD/2;
tpr=t-ITD/2;

%Gaussian Bandlimited Noise
%X=noiseblfft(f1,f2,Fs,M);
X=noiseblh(f1,f2,Fs,M,seed,'y');

%Time Warping the left and right sounds
Xl=interp1(tpl,X,t,'cubic');
Xr=interp1(tpr,X,t,'cubic');

%BandPass Filtering to remove spectral splatter due to time warping and
%interpolation artifact (i.e., crappy interpolator)
ATT=60;
H=bandpass(f1,f2,.1*(f2-f1)/2,Fs,ATT,'n');
N=(length(H)-1)/2;
NFFT=2^nextpow2(N+M);
Xl=convfft(Xl,H,N,NFFT);
Xr=convfft(Xr,H,N,NFFT);
Xl=Xl(1:M);
Xr=Xr(1:M);