function nDoRate()
    
hRT=findobj('tag','RateFig');
if ~isempty(hRT),
    figure(hRT);
  else
    a = figure('Color',[0.8 0.8 0.8], ...
      'Units', 'points', ...
      'Name', 'rate', ...
      'Menubar','none', ...
    	'Position',[10 10 365 290], ...
    	'Tag','RateFig');
    b = axes('Parent',a, ...
            'ButtonDownFcn', 'pickRate', ...
    	'CameraUpVector',[0 1 0], ...
    	'CameraUpVectorMode','manual', ...
    	'Color',[1 1 1], ...
    	'Position',[0.126 0.511 0.823 0.415], ...
    	'Tag','RateAxes', ...
    	'XColor',[0 0 0], ...
    	'YColor',[0 0 0], ...
    	'ZColor',[0 0 0]);
    c = text('Parent',b, ...
    	'Color',[0 0 0], ...
    	'HandleVisibility','callback', ...
    	'HorizontalAlignment','center', ...
    	'Position',[0.498 -0.133 0], ...
    	'Tag','Text1', ...
    	'VerticalAlignment','cap');
    set(get(c,'Parent'),'XLabel',c);
    c = text('Parent',b, ...
    	'Color',[0 0 0], ...
    	'HandleVisibility','callback', ...
    	'HorizontalAlignment','center', ...
    	'Position',[-0.072 0.504 0], ...
    	'Rotation',90, ...
    	'Tag','Text2', ...
    	'VerticalAlignment','baseline');
    set(get(c,'Parent'),'YLabel',c);
    c = text('Parent',b, ...
    	'Color',[0 0 0], ...
    	'HandleVisibility','callback', ...
    	'HorizontalAlignment','right', ...
    	'Position',[-0.155 1.181 0], ...
    	'Tag','Text3', ...
    	'Visible','off');
    set(get(c,'Parent'),'ZLabel',c);
    c = text('Parent',b, ...
    	'Color',[0 0 0], ...
    	'HandleVisibility','callback', ...
    	'HorizontalAlignment','center', ...
    	'Position',[0.498 1.052 0], ...
    	'Tag','Text4', ...
    	'VerticalAlignment','bottom');
    set(get(c,'Parent'),'Title',c);
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Position',[11.527 49.952 156.583 67.244], ...
    	'Style','frame', ...
    	'Tag','Frame1');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Position',[61.480 95.102 60.519 19.212], ...
    	'String','Range', ...
    	'Style','text', ...
    	'Tag','StaticText1');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback','rateRangeRadios', ...
    	'Position',[16.330 77.330 59.559 19.212], ...
    	'String','CF', ...
    	'Style','radiobutton', ...
    	'Value', 1, ...
    	'Tag','RateCFRadio');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.701 0.701 0.701], ...
    	'Callback','rateRangeRadios', ...
      'Enable', 'off', ...
    	'Position',[16.330 55.716 59.559 19.212], ...
    	'String','Marked', ...
    	'Style','radiobutton', ...
    	'Tag','RateMarkedRadio', ...
    	'Value',0);
    b = uicontrol('Parent',a, ...
            'Units','points', ...
            'BackgroundColor',[1 1 1], ...
            'Enable','inactive', ...
            'HorizontalAlignment','left', ...
            'Position',[76.850 77.330 86.456 19.212], ...
            'String','', ...
            'Style','edit', ...
            'Tag','RateFreqEdit');
    %b = uicontrol('Parent',a, ...
    %        'Units','points', ...
    %        'BackgroundColor',[1 1 1], ...
    %        'Enable','inactive', ...
    %        'HorizontalAlignment','left', ...
    %        'Position',[77.811 55.716 86.456 19.212], ...
    %        'String',' 12.1 -  72.8 dB', ...
    %        'Style','edit', ...
    %        'Tag','RateAmpEdit');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Position',[175.795 49.952 173.874 67.244], ...
    	'Style','frame', ...
    	'Tag','Frame2');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Position',[241.118 96.543 57.637 16.330], ...
    	'String','Mark', ...
    	'Style','text', ...
    	'Tag','StaticText2');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback', 'rateMarkRadios', ...
    	'ForegroundColor',[1 0 0], ...
    	'Position',[179.638 77.330 82.614 19.212], ...
    	'String','Threshold', ...
    	'Style','radiobutton', ...
    	'Value', 1, ...
    	'Tag','RateThreshRadio');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback', 'rateMarkRadios', ...
    	'ForegroundColor',[0 0 1], ...
    	'Position',[264.173 77.330 79.732 19.212], ...
    	'String','Trans Pt', ...
    	'Style','radiobutton', ...
    	'Value', 0, ...
    	'Tag','RateTransitionRadio');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback', 'rateMarkRadios', ...
    	'ForegroundColor',[1 0 1], ...
    	'Position',[179.638 55.716 80.692 19.212], ...
    	'String','Endpoint', ...
    	'Style','radiobutton', ...
    	'Value', 0, ...
    	'Tag','RateEndRadio');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback', 'rateMarkRadios', ...
    	'ForegroundColor',[0.5 0.3 0], ...
    	'Position',[264.173 55.716 78.771 19.212], ...
    	'String','Best Ampl', ...
    	'Style','radiobutton', ...
    	'Value', 0, ...
    	'Tag','BestAmplRadio');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[1 1 1], ...
    	'Enable','inactive', ...
      'HorizontalAlignment','left', ...
    	'Position',[8.645 6.724 342.945 19.212], ...
    	'Style','edit', ...
    	'Tag','RateMessages');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback', 'rateAccept', ...
    	'Position',[225 30 60 20], ...
    	'String','Accept', ...
    	'Tag','RateAcceptButton');
    b = uicontrol('Parent',a, ...
    	'Units','points', ...
    	'BackgroundColor',[0.7 0.7 0.7], ...
    	'Callback', 'deleteFig', ...
    	'Position',[290 30 60 20], ...
    	'String','Dismiss', ...
    	'Tag','RateDismissButton');
      
    b = uimenu('Label', 'Print', 'Tag', 'PrintMenu');
    c = uimenu(b, 'Label', 'Page Position...', ...
            'Callback', 'pagedlg');
    c = uimenu(b, 'Label', 'Print All...', ...
            'Callback', 'printdlg');
    c = uimenu(b, 'Label', 'Print Axes...', ...
            'Callback', 'printAxes');
 
    b = uimenu(a, 'Label', 'Window', ...
       'Callback', winmenu('callback'), 'Tag', 'winmenu');
    winmenu(a);  % Initialize the submenu
    
  end % (if)

return
