function fig = nDoTC()

INCLUDE_DEFS;

%%%------- main figure definition

h0 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',rainbow(64), ...
	'MenuBar','none', ...
	'Name','tuning curve', ...
	'Position',[0.551 0.058 0.425 0.526], ...
	'Renderer','zbuffer', ...
	'RendererMode','manual', ...
	'ResizeFcn','resizeNTCFig', ...
	'Tag','TuningCurveFig');

%%%-------- menu items

h1 = uimenu('Parent',h0, ...
	'Label','Print', ...
	'Tag','PrintMenu');

h2 = uimenu('Parent',h1, ...
	'Callback','pagedlg', ...
	'Label','Page Position...', ...
	'Tag','PrintPage Position...1');

h2 = uimenu('Parent',h1, ...
	'Callback','printdlg', ...
	'Label','Print All...', ...
	'Tag','PrintPrint All...1');

h2 = uimenu('Parent',h1, ...
	'Callback','printAxes', ...
	'Label','Print Axes...', ...
	'Tag','PrintPrint Axes...1');

h1 = uimenu('Parent',h0, ...
	'Callback','winmenu', ...
	'Label','Window', ...
	'Tag','winmenu');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Tag','WindowMenu1', ...
	'Visible','off');

h2 = uimenu('Parent',h1, ...
	'Callback','figure(1)', ...
	'Label','Figure No. 1: tuning curve', ...
	'Tag','WindowFigure No. 1: tuning curve1');

h2 = uimenu('Parent',h1, ...
	'Callback','figure(135.000)', ...
	'Label','Guide Control Panel', ...
	'Tag','WindowGuide Control Panel1');

h1 = uimenu('Parent',h0, ...
	'Label','Display', ...
	'Tag','DisplayMenu');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Checked','on', ...
	'Label','Lines', ...
	'Tag','LinesOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Label','PColor', ...
	'Tag','ColorOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Label','Contour', ...
	'Tag','ContourOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Label','Surface', ...
	'Tag','SurfaceOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Label','RasterByFreq', ...
	'Tag','FreqRasterOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Label','RasterByInt', ...
	'Tag','IntRasterOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setDisplayType; refreshDisplay', ...
	'Label','TwoLines', ...
	'Tag','Lines2Option');

h1 = uimenu('Parent',h0, ...
	'Label','Smoothing ', ...
	'Tag','SmoothMenu');

h2 = uimenu('Parent',h1, ...
	'Callback','setSmoothing; refreshDisplay', ...
	'Checked','on', ...
	'Label','NoSmooth', ...
	'Tag','NoSmoothOption');

h2 = uimenu('Parent',h1, ...
	'Callback','setSmoothing; refreshDisplay', ...
	'Label','Smooth1', ...
	'Separator','on', ...
	'Tag','Smooth1Option');

h2 = uimenu('Parent',h1, ...
	'Callback','setSmoothing; refreshDisplay', ...
	'Label','Smooth2', ...
	'Tag','Smooth2Option');

h2 = uimenu('Parent',h1, ...
	'Callback','setSmoothing; refreshDisplay', ...
	'Label','MedianSmooth', ...
	'Tag','SmoothMOption');

h1 = uimenu('Parent',h0, ...
	'Label','Preferences', ...
	'Tag','PreferenceMenu');

h2 = uimenu('Parent',h1, ...
	'Callback','loadPrefs', ...
	'Label','Load...', ...
	'Tag','loadPrefsOption');

h2 = uimenu('Parent',h1, ...
	'Callback','savePrefs', ...
	'Label','Save...', ...
	'Tag','savePrefsOption');

h2 = uimenu('Parent',h1, ...
	'Callback','modPrefs', ...
	'Label','Modify...', ...
	'Separator','on', ...
	'Tag','modPrefsOption');

h2 = uimenu('Parent',h1, ...
	'Callback','applyPrefs; refreshDisplay', ...
	'Label','Apply', ...
	'Tag','applyPrefsOption');

h1 = uimenu('Parent',h0, ...
	'Label','Font', ...
	'Tag','FontMenu');

h2 = uimenu('Parent',h1, ...
	'Callback','modNTCFonts(''Smaller'')', ...
	'Label','Smaller', ...
	'Tag','smallerFontMenu');

h2 = uimenu('Parent',h1, ...
	'Callback','modNTCFonts(''Larger'')', ...
	'Label','Larger', ...
	'Tag','largerFontMenu');

h1 = uimenu('Parent',h0, ...
	'Callback','helpntc', ...
	'Label','Help', ...
	'Tag','HelpMenu');

%%%------- data axes

h1 = axes('Parent',h0, ...
	'FontUnits','normalized', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',defColorOrder, ...
	'DrawMode','fast', ...
	'FontSize',0.039, ...
	'Layer','top', ...
	'NextPlot','replacechildren', ...
	'Position',[0.181 0.148 0.578 0.489], ...
	'Tag','TuningCurveAxes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498 -0.072 9.160], ...
	'Tag','Text1', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.073 0.494 9.160], ...
	'Rotation',90, ...
	'Tag','Text2', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.316 1.737 9.160], ...
	'Tag','Text3', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.496        1.019       9.160] , ...
	'Tag','Text4', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);

%%%-------- colorbar axes

h1 = axes('Parent',h0, ...
	'FontUnits','normalized', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',defColorOrder, ...
	'FontSize',0.039, ...
	'Layer','top', ...
	'NextPlot','add', ...
	'Position',[0.781 0.148 0.028 0.489], ...
	'Tag','ColorBar', ...
	'UserData',42.001, ...
	'XColor',[0 0 0], ...
	'XLim',[-1 1], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YAxisLocation','right', ...
	'YColor',[0 0 0], ...
	'YLim',[1 65], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.066 -0.460 9.160], ...
	'Tag','Text5', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[3.399 32.634 9.160], ...
	'Rotation',90, ...
	'Tag','Text6', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'YLabel',h2);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[ -61.857       112.21       9.160], ...
	'Tag','Text7', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);

h2 = text('Parent',h1, ...
	'FontUnits','normalized', ...
	'Color',[0 0 0], ...
	'FontSize',0.039, ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.066 66.216 9.160], ...
	'Tag','Text8', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);

%%%-------- decorations, buttons, and static text

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.167, ...
	'ListboxTop',0, ...
	'Position',[0.848 0.24 0.143 0.096], ...
	'Style','frame', ...
	'Tag','Frame5');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.247, ...
	'ListboxTop',0, ...
	'Position',[0.008 0.865 0.981 0.06], ...
	'Style','frame', ...
	'Tag','Frame8');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.242, ...
	'ListboxTop',0, ...
	'Position',[0.008 0.929 0.981 0.06], ...
	'Style','frame', ...
	'Tag','Frame7');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.452, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.133 0.944 0.095 0.024], ...
	'String','Directory:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','readAndDisplayFile', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.562 0.935 0.116 0.04], ...
	'String','Read File:', ...
	'Tag','ReadFileButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','readNextFile', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.915 0.935 0.068 0.04], ...
	'String','Next', ...
	'Tag','NextButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.433, ...
	'ListboxTop',0, ...
	'Position',[0.017 0.944 0.070 0.026], ...
	'String','Data', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.032, ...
	'ListboxTop',0, ...
	'Position',[0.008 0.204 0.095 0.582], ...
	'Style','frame', ...
	'Tag','Frame2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.242, ...
	'ListboxTop',0, ...
	'Position',[0.008 0.796 0.981 0.062], ...
	'Style','frame', ...
	'Tag','Frame3');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.433, ...
	'ListboxTop',0, ...
	'Position',[0.017 0.879 0.11 0.026], ...
	'String','Attributes', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.433, ...
	'ListboxTop',0, ...
	'Position',[0.017 0.814 0.11 0.026], ...
	'String','Output File', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','measure', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.703 0.066 0.04], ...
	'String','CF', ...
	'Tag','CFButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','appendAttributes', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.877 0.87 0.085 0.04], ...
	'String','Append', ...
	'Tag','AppendButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','showAttributes(mkColHeaders);', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.743 0.87 0.114 0.04], ...
	'String','Show New', ...
	'Tag','ShowButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','showFileNums;', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.61 0.87 0.114 0.04], ...
	'String','Show Files', ...
	'Tag','ShowFilesButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.050, ...
	'ListboxTop',0, ...
	'Position',[0.848 0.42 0.143 0.366], ...
	'Style','frame', ...
	'Tag','Frame1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','sharp', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.649 0.066 0.04], ...
	'String','Q10', ...
	'Tag','Q10Button');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','sharp', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.594 0.066 0.04], ...
	'String','Q20', ...
	'Tag','Q20Button');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','sharp', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.54 0.066 0.04], ...
	'String','Q30', ...
	'Tag','Q30Button');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','sharp', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.485 0.066 0.04], ...
	'String','Q40', ...
	'Tag','Q40Button');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','sharp', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.431 0.066 0.04], ...
	'String','All', ...
	'Tag','AllButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','doLatency', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.376 0.066 0.04], ...
	'String','Lat', ...
	'Tag','LatencyButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','doHist', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.322 0.066 0.04], ...
	'String','Histo', ...
	'Tag','HistogramButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','doRate', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.267 0.066 0.04], ...
	'String','Rate', ...
	'Tag','RateButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','measure', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.022 0.213 0.066 0.04], ...
	'String','Point', ...
	'Tag','PointButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Enable','off', ...
	'FontSize',0.416, ...
	'ListboxTop',0, ...
	'Position',[0.953 0.604 0.032 0.028], ...
	'String','%', ...
	'Style','text', ...
	'Tag','PercentStaticText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','toggleBlind', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.703 0.114 0.04], ...
	'String','Blind', ...
	'Style','checkbox', ...
	'Tag','BlindBox');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','spontButton;refreshDisplay', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.648 0.114 0.04], ...
	'String','Spont', ...
	'Style','checkbox', ...
	'Tag','SpontBox');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','refreshDisplay', ...
	'FontSize',0.315, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.43 0.125 0.042], ...
	'String','Refresh', ...
	'Tag','RefreshButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[0.114 0.648 0.724 0.138], ...
	'Style','frame', ...
	'Tag','Frame4');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.133 0.741 0.095 0.022], ...
	'String','Time Slice', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.433, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.749 0.114 0.025], ...
	'String','Display', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.452, ...
	'ListboxTop',0, ...
	'Position',[0.017 0.749 0.08 0.024], ...
	'String','Measure', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','moveButton', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.123 0.657 0.068 0.04], ...
	'String','rev', ...
	'Tag','ReverseButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','moveButton', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.19 0.657 0.068 0.04], ...
	'String','half', ...
	'Tag','HalfReverseButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','moveButton', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.762 0.657 0.068 0.04], ...
	'String','fwd', ...
	'Tag','ForwardButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','moveButton', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Position',[0.695 0.657 0.068 0.04], ...
	'String','half', ...
	'Tag','HalfForwardButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.362 0.661 0.076 0.022], ...
	'String','Range:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.51 0.661 0.03 0.022], ...
	'String','to', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','saveAttributes', ...
	'FontSize',0.325, ...
	'ListboxTop',0, ...
	'Position',[0.562 0.801 0.116 0.04], ...
	'String','Save to File:', ...
	'Tag','SaveButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.133 0.814 0.095 0.022], ...
	'String','Directory:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','moviePopup', ...
	'FontSize',0.315, ...
	'ListboxTop',0, ...
	'Max',2, ...
	'Min',1, ...
	'Position',[0.008 0.148 0.125 0.042], ...
	'String',['Film';'Play'], ...
	'Style','popupmenu', ...
	'Tag','MoviePopup', ...
	'Value',1);

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.61 0.661 0.035 0.022], ...
	'String','ms', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.783 0.741 0.041 0.022], ...
	'String','ms', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.452, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.408 0.741 0.064 0.024], ...
	'String','0.0', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.452, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.314 0.741 0.095 0.024], ...
	'String','Start:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.629 0.741 0.076 0.022], ...
	'String','100.0', ...
	'Style','text', ...
	'Tag','StaticMaxTime');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','updateFromSliders; refreshDisplay', ...
	'FontSize',0.371, ...
	'ListboxTop',0, ...
	'Max',100, ...
	'Position',[0.476 0.741 0.152 0.034], ...
	'Style','slider', ...
	'Tag','StartSlider', ...
	'Value',10);

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','updateFromSliders; refreshDisplay', ...
	'FontSize',0.358, ...
	'ListboxTop',0, ...
	'Max',100, ...
	'Position',[0.476 0.703 0.152 0.034], ...
	'Style','slider', ...
	'Tag','DurationSlider', ...
	'Value',10);

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.629 0.713 0.076 0.022], ...
	'String','100.0', ...
	'Style','text', ...
	'Tag','StaticMaxTime');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.452, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.314 0.713 0.095 0.024], ...
	'String','Duration:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.452, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.408 0.713 0.066 0.024], ...
	'String','0.0', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.783 0.713 0.041 0.022], ...
	'String','ms', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.008 0.086 0.2 0.022], ...
	'String','Ext. Atten. (dB)  C:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.247 0.086 0.028 0.022], ...
	'String','I:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.877 0.05 0.047 0.022], ...
	'String','unit:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.086 0.066 0.022], ...
	'String','depth:', ...
	'Style','text', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','inactive', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.008 0.042 0.838 0.036], ...
	'Style','edit', ...
	'Tag','MessageText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','zapStimPoint', ...
	'FontSize',0.315, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.148 0.125 0.042], ...
	'String','Zap Points', ...
	'Tag','ZapButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','zapStimRange', ...
	'Enable','off', ...
	'FontSize',0.315, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.194 0.125 0.042], ...
	'String','Zap Range', ...
	'Tag','ZapRangeButton');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','markEtcButton', ...
	'FontSize',0.315, ...
	'ListboxTop',0, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[0.858 0.252 0.125 0.042], ...
	'String',['Meas ';'Zoom ';'Spont'], ...
	'Style','popupmenu', ...
	'Tag','markEtcRadio', ...
	'Value',1);

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','setScale; refreshDisplay', ...
	'FontSize',0.335, ...
	'ListboxTop',0, ...
	'Max',2, ...
	'Min',1, ...
	'Position',[0.858 0.54 0.114 0.04], ...
	'String',['Fixed';'Float'], ...
	'Style','popupmenu', ...
	'Tag','ScalePopup', ...
	'Value',2);

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Enable','off', ...
	'FontSize',0.416, ...
	'ListboxTop',0, ...
	'Position',[0.915 0.495 0.061 0.028], ...
	'String','spikes', ...
	'Style','text', ...
	'Tag','StaticTextSpikes');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',0.371, ...
	'ListboxTop',0, ...
	'Position',[0.858 0.296 0.11 0.034], ...
	'String','Pick Area', ...
	'Style','text', ...
	'Tag','StaticText3');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',0.473, ...
	'ListboxTop',0, ...
	'Position',[0.008 0.012 0.12 0.022], ...
	'String','Comments:', ...
	'Style','text', ...
	'Tag','StaticTextComments');

%%%---------- editable text items

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.228 0.935 0.324 0.036], ...
	'String','.', ...
	'Style','edit', ...
	'Tag','InfileDirectoryText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','readAndDisplayFile', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.676 0.935 0.15 0.036], ...
	'String','sc172109.dtc', ...
	'Style','edit', ...
	'Tag','InfileText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.228 0.801 0.324 0.036], ...
	'String','/tmp', ...
	'Style','edit', ...
	'Tag','OutdirectoryText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','saveAttributes', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.676 0.801 0.15 0.036], ...
	'String','outfile.mat', ...
	'Style','edit', ...
	'Tag','OutfileText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','updateFromSliderText; refreshDisplay', ...
	'FontSize',0.358, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.705 0.741 0.076 0.036], ...
	'String','10.0', ...
	'Style','edit', ...
	'Tag','StartText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','updateFromSliderText; refreshDisplay', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.705 0.703 0.076 0.036], ...
	'String','10.0', ...
	'Style','edit', ...
	'Tag','DurationText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','updateFromRange; refreshDisplay', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.438 0.653 0.070 0.036], ...
	'String','10.0', ...
	'Style','edit', ...
	'Tag','RangeStartText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','updateFromRange; refreshDisplay', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.538 0.653 0.070 0.036], ...
	'String','20.0', ...
	'Style','edit', ...
	'Tag','RangeEndText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','refreshDisplay', ...
	'Enable','off', ...
	'FontSize',0.358, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.896 0.604 0.053 0.036], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','PercentEdit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','refreshDisplay', ...
	'Enable','off', ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.858 0.495 0.053 0.036], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','ScaleText');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','enterNewAtten', ...
	'FontSize',0.358, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.2 0.08 0.047 0.036], ...
	'String','99', ...
	'Style','edit', ...
	'Tag','AttenCEdit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','enterNewAtten', ...
	'FontSize',0.358, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.276 0.08 0.047 0.036], ...
	'String','99', ...
	'Style','edit', ...
	'Tag','AttenIEdit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.358, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.924 0.08 0.066 0.036], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','DepthEdit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.347, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.924 0.042 0.066 0.036], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','UnitEdit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.335, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.125 0.005 0.87 0.038], ...
	'String','<add comments here>', ...
	'Style','edit', ...
	'Tag','TCCommentEdit');
if nargout > 0, fig = h0; end

return
