%SHUFFLE_R_ACROSS_CELLS Randomly permutes, independently for each cell, the
% order of trials collected in response to each stimulus.
%
%   ------
%   SYNTAX
%   ------
%       Rsh = shuffle_R_across_cells(R, nt)
%
%   ---------
%   ARGUMENTS
%   ---------
%   R  - response matrix
%   nt - number of trials available for each per stimulus

%   Copyright (C) 2009 Cesare Magri
%
%   License
%   -------
%   This code is distributed free under the condition that
%   1. it shall not be incorporated in software that is subsequently sold;
%   2. the authorship of the software shall be acknowledged in any 
%      pubblication that uses results generated by the software;
%   3. this note shall remain in place in each source file.