function logical_mask = build_logical_mask(nt, maxNt, Ns)

%   Copyright (C) 2009 Cesare Magri
%   Version: 1.0.4

% LICENSE
% -------
% The Information Breakdown ToolBox (ibTB) is distributed free under the
% condition that:
% 1 - it shall not be incorporated in software that is subsequently sold;
% 2 - the authorship of the software shall be acknowledged in any
%     pubblication that uses results generated by the software;
% 3 - this notice shall remain in place in each source file.

column_increment = 0:maxNt:(Ns*maxNt)-1;

mask = zeros(maxNt, Ns);
mask(column_increment + nt(:).') = 1;
mask(end:-1:1,:) = cumsum(mask(end:-1:1,:));
% Converting 1 to logical "true":
logical_mask = mask>0;